### ISSUE TITLE
restart reproducibility (without waves) when USE_LA_LI2016=True

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/MOM6#46]
When running the regression tests without waves for restart reproducibility, USE_LA_LI2016 is set to false to reproduce.  Further description from @DeniseWorthen:  This is a long-standing issue where the grid decomposition appears in the MOM6 fields after restart if this parameter is set true. It was not resolved when we switched to vertex_shear=F in the update to MOM6 (PR #290).

**Comment by DeniseWorthen** [comment]
I have created a reproducer branch [here](https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/mom6repro).

This branch contains additional settings and tests which reproduce the restart issue at C96mx100. Two additional control and restart tests are added demonstrating that:

a) when ``USE_LA_LI2016=True``, the MOM6 grid decomposition appears on restart
b) when ``USE_LA_LI2016=True`` AND ``WIND_STAGGER=C``, the MOM6 grid decomposition does not appear on restart.

When running this test branch, the results are not being compared against the baseline. The control and restart runs are being compared directly in this case, therefore the "LIST_FILES" within the tests is an empty string. Also, all components and coupling is being done at a single DT, removing any possible averaging effects.

The tests can be run using: ./rt.sh -ek -l rt.cpldrestart.conf >output 2>&1 &

These results are contained within the coupler history files, which are written at every time timestep. The coupler history file _ufs.cpld.cpl.hi.2016-10-03-04500.nc_ in the restart run should be compared to the same coupler history file for the continuous run. 

When comparing _ufs.cpld.cpl.hi.2016-10-03-04500.nc_ between restart and continuous runs for the ``USE_LA_LI2016=True`` case, three fields do not reproduce: _ocnImp_So_s_, _ocnImp_So_t_ and _ocnImp_Fioo_q_. These are the salinity (So_s), temperature (So_t) and freeze/melt potential (Fioo_q) that are imports to the mediator from the ocean (ocnImp) at the end of the first timestep after restart. The following figure shows the difference for _ocnImp_So_t_ for between the continuous and restart run: 

<img width="804" alt="Screen Shot 2021-01-11 at 8 38 31 AM" src="https://user-images.githubusercontent.com/40498404/104191208-35cd5080-53eb-11eb-8740-61fbb9b9dde7.png">

**Comment by DeniseWorthen** [comment]
I've been able to run the coupled model on gaea in this branch and reproduce the error.

**Comment by JessicaMeixner-NOAA** [comment]
@breichl the code and test case should now work on Gaea.

**Comment by DeniseWorthen** [comment]
My latest test run on Gaea is :/lustre/f2/scratch/Denise.Worthen/FV3_RT/rt_25674

**Comment by breichl** [comment]
Is there an instruction to build the executable on Gaea?  I tried to run/understand the test script in the tests folder as above, but I seem to be missing something as nothing is happening.  I then tried to build from build.sh, which asks for ESMFMKFILE environment variable to be set.  Not sure what this should be.  Unfortunately I can't look at your directory for guidance, I assume because there aren't cross-permissions between GFDL/EMC accounts.

**Comment by DeniseWorthen** [comment]
I suspect you'll need to export an accnr variable. I used "export ACCNR=nggps_emc", justin uses "export ACCNR=gfdl_b"

I don't know why build.sh doesn't work, but Justin got the same behaviour. I must have something to do w/ how gaea uses modules. I used the standard method, which is shown in this screenshot, where you first load the required modules:

<img width="751" alt="Screen Shot 2021-01-13 at 2 23 28 PM" src="https://user-images.githubusercontent.com/40498404/104635981-ac2eb480-5670-11eb-9807-f6c8a1d1c6d2.png">

Using rt.sh (ie, ./rt.sh -ek -l rt.cpldrestart.conf >output 2>&1 &), the run directory will be created /lustre/f2/scratch/username/FV3_RT/rt_number

**Comment by breichl** [comment]
Thanks Denise.  I seem to be failing in the "module purge" step of "module-setup.sh.inc" within rt.sh.  I've pinged Justin to see if he is familiar with this.

**Comment by breichl** [comment]
I think its running now.  I'll keep you posted if I can spot the issue.

**Comment by breichl** [comment]
It looks to me like there are missing halo updates on taux and tauy in A&B grid configurations.  The changes here appear to fix the restart issue: https://github.com/breichl/MOM6/tree/user/bgr/Tau_halo_updates_in_nupoc

**Comment by DeniseWorthen** [comment]
@breichl Thanks--let me give it a try. So this lack of halo update must be benign when the LI_2016 is not used, is that right?

**Comment by breichl** [comment]
It appears so, which indicates that it matters only because taux/tauy is used to set ustar_gustless on cell centers (via set_derived_forcing_fields in mom_ocean_model_nuopc).  ustar_gustless is only used when LI_2016 is true.  I presume ustar_gustless is the only place where taux/tauy are averaged to cell centers (the ustar averaging, for example, is computed from other terms within these loops, hence ustar is not sensitive to the halo update).  The halo updates are there for the C-grid already, hence the C-grid case working.  So this fix seems consistent with all the symptoms.

**Comment by DeniseWorthen** [comment]
I've tested in all our non-wave benchmark configurations and they all pass the restart test now so I think you correctly isolated and solved the issue. Would you like to make a PR back to noaa-emc w/ the fix or should I use my fork (with you credited w/ fix)?

**Comment by breichl** [comment]
Just sent it up, but feel free to use yours if its easier.

**Comment by DeniseWorthen** [comment]
No, that is fine. Thanks. I know Jiande wants to wait on MOM6 updates until the new FMS is ready. So I'm not sure of the exact timing.

This PR will also need an issue on ufs-weather so I'll create that.

**Comment by jiandewang** [comment]
close
