### ISSUE TITLE
ocean mask created at run time is not same as ocean mask in INPUT for the 1deg configuration

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/MOM6#47]
For the 1deg model, the ocean mask in INPUT/ocean_mask.nc differs at a single location from the ocean mask produced at run time (MOM6_OUTPUT/ocean_geometry). The difference is located at i=88,j=133. 

I did not think that the land mask could be changed at run time, only the bathymetry. 

This affects the creation of the mapped ocean mask files for the frac grid, since in that case the ocean land mask is consistent with the INPUT/ocean_mask file.

In the 1/2 and 1/4 deg case, the INPUT/ocean_mask file and the MOM6_OUTPUT/ocean_geometry files are consistent.

**Comment by DeniseWorthen** [comment]
This is the mask from INPUT/ocean_mask:
<img width="817" alt="Screen Shot 2021-01-08 at 11 19 48 AM" src="https://user-images.githubusercontent.com/40498404/104047068-0b8f4f00-51af-11eb-916a-dcd3f55cca82.png">

And from MOM6_OUTPUT/ocean_geometry:
<img width="804" alt="Screen Shot 2021-01-08 at 11 20 04 AM" src="https://user-images.githubusercontent.com/40498404/104047111-1b0e9800-51af-11eb-9def-2b8c3fd6d8ef.png">

**Comment by jiandewang** [comment]
@DeniseWorthen the way MOM is designed is first reading in grid file, then make some adjustment on certain grid points to have better currents and throughflows. This is done by further reading in a fixed file "topo_edits.nc" which contains the new depth values to override the original one. Usually these adjustments are to make the ocean points deepen or shallower to control throughflow. However in 1x1 setting, there is one land point in Indonesia area (i=88,j=132) whose depth has been changed from 0 to 1000m.
![image](https://user-images.githubusercontent.com/14180427/106233426-8a7f1280-61c4-11eb-9f4c-0dced3043d4c.png)


By looking at mesh file, it is generated by read in "Ct.mx100_SCRIP_land.nc" which I believe is generated from the original topo.nc file. Can we use an alternative source file (for example geometry file) to generate "Ct.mx100_SCRIP_land.nc" ?

**Comment by DeniseWorthen** [comment]
The ocean_geometry file is generated at run time. We should not have a system where we need to run the model in order to generate a fixed file to run the model.

The file Ct.mx100_SCRIP_land.nc is generated using the file tripole.mx100.nc. This file is generated from by reading only two files, the ocean_hgrid.nc and the ocean_mask.nc. The topo.nc file is not used.

I see now the point in the topo_edits_011818.nc file. I had missed it earlier because it is out of order (the preceding point is at i=219 and the next point is i=292). 

I still don't understand why when it reads the edits file, it is allowing the land mask to change. Doesn't this indicate that is not allowed? https://github.com/NOAA-EMC/MOM6/blob/d531a324a91f5de652055cbd8adfd84c4e75be30/src/initialization/MOM_shared_initialization.F90#L290

**Comment by JessicaMeixner-NOAA** [comment]
Another question:  I doubt this topo_edits_file is file is being used when the atm model is generating it's fractional land mask  If the land mask is allowed to change based on this topo edits file, that's probably an issue with all of the fractional grid generation...

**Comment by DeniseWorthen** [comment]
Yes, you are correct. As I noted, the mapped ocean mask files generated for FV3 depend on the ocean mask not changing at run-time.

**Comment by JessicaMeixner-NOAA** [comment]
Thanks!

**Comment by jiandewang** [comment]
https://github.com/NOAA-EMC/MOM6/blob/d531a324a91f5de652055cbd8adfd84c4e75be30/src/initialization/MOM_shared_initialization.F90#L284-L290
I think here it allows for the changing from land to ocean, but not the other way.

**Comment by DeniseWorthen** [comment]
OK, I guess I see that from the code, that it is saying that 'new_depth' can't be zero---in other words, you can't take away an ocean point (no ocean->land is allowed). 

But the other way around is just as bad---you're still changing the land mask in converting land->ocean which is the same problem that triggers the FATAL above.
