### ISSUE TITLE
bug fix: sign error in fprec passed to ocean in caps

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/MOM6#53]
NCAR has notified us that they found a sign error in the latent heat contribution for frozen precip  (fprec) being passed to ocean in both the mct and nuopc caps. The required change is shown [here](https://github.com/NCAR/MOM6/commit/230b839ba25a3b03247563e2a0b01796114d8b75). 

Since this is a bug fix, we should merge the fix now rather than waiting for the change to come back in the next update from GFDL.

**Comment by jiandewang** [comment]
close
