### ISSUE TITLE
threading

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/MOM6#57]
Investigate/implement threadding for MOM6. Currently the UFS coupled model builds MOM6 without threadding.  However, if other models require running with threads and task geometry is not use for the forecast model, having the capability use threading for MOM6 could be helpful.

**Comment by jiandewang** [comment]
from Moorthi (20210513 email): 

"I finally decided to try the threading issue again and It looks like MOM6 reproduces in the coupled model with 1 and 2 threads.
Maybe using mommesh might be the reason."

"I tested with different number mpi tasks (for MOM6) too and they are reproducing"

**Comment by jiandewang** [comment]
close
