### ISSUE TITLE
Use of imported sea level pressure for the 1deg configuration

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/MOM6#58]
During development required for ufs-weather-model [#366](https://github.com/ufs-community/ufs-weather-model/issues/366) it was determined that the 1deg MOM6 configuration is not making use of the sea level pressure imported from the mom6 cap. 

The behaviour noted is that changing the mapping method of sea level pressure from atm->ocn in the CMEPS mediator produced bit identical results for the C96mx100 configuration. Since the values of sea level pressure did in fact change when the mapping method was changed, this means that MOM6 is apparently not using the imported sea level pressure in the 1deg configuration.

Testing of the C192mx050 configuration showed that the change of mapping method for sea level pressure did in fact change answers.

I have not been able to determine the MOM6 configuration setting which is controlling the different behavior of the 1deg vs 1/2 deg configuration.

**Comment by jiandewang** [comment]
@DeniseWorthen I will ask this question to GFDL. Apparently there is one switch that is turned on in 1/2 deg configuration but not in 1x1 deg configuration. The default value of this switch must be False.

**Comment by jiandewang** [comment]
@DeniseWorthen I found out the parameter, it is DYNAMIC_SURFACE_PRESSURE. It does not appear in 1x1 MOM_input but it is setup as True in half degree MOM_input. Default value is False.

**Comment by DeniseWorthen** [comment]
@jiandewang Thanks. So our general rule is to keep parameters identical to GFDL where possible so you're suggesting we retain this as the default (False) value for our 1deg config?

**Comment by DeniseWorthen** [comment]
Closing this issue since we know the relevant parameter which results in the 1deg configuration to be independent of atm surface pressure. We need to keep this situation in mind though. It is a perfect illustration of why testing a single MOM6 resolution is not sufficient.
