### ISSUE TITLE
Add IAU capability to MOM6

### ISSUE THREAD

**Issue by pjpegion** [NOAA-EMC/MOM6#69]
Alex Bozec and Alan Wallcraft from COAPS/Florida State University have developed Incremental analysis update capability for MOM6. An older commit has been tested in the UFS-datm with a "replay" to ORAS5 analysis.  I will test it out the latest updates once hera come back online.

There will be an assoicate PR in the ufs-weather-model to modify the CMakeLists.txt file and add a IAU regression test to ocean model.

Draft PR is https://github.com/NOAA-EMC/MOM6/pull/68

**Comment by jiandewang** [comment]
close
