### ISSUE TITLE
update MOM6 to 20220317 commit

### ISSUE THREAD

**Issue by jiandewang** [NOAA-EMC/MOM6#86]
MOM6 main branch was updated on 20220317 (see detail at https://github.com/mom-ocean/MOM6/pull/1559), this is based on FSU Alex "add call to restart_registry_lock when setting up ODA at initialization" PR. Need to update dev/emc correspondingly.

**Comment by pjpegion** [comment]
I'm testing this now.  and I will give you a new regression test to add at the ufs-weather-model level.

**Comment by pjpegion** [comment]
IAU is working fine.  I have the new test, but it sounds like the regression tests are already running, so I will get it in the next one.

**Comment by jiandewang** [comment]
@pjpegion we are in a hurry to have this code update in dev/emc in order to have GFDL's FMS mixed mode code PR, we can get yours in next time. Thanks.

**Comment by jiandewang** [comment]
this is combined and done with https://github.com/ufs-community/ufs-weather-model/pull/1136
