### ISSUE TITLE
Allow MOM6 to write restarts at a end of run in addition to at a restart frequency

### ISSUE THREAD

**Issue by DeniseWorthen** [NOAA-EMC/MOM6#90]
Currently as implemented in UFS, MOM6 can write a restart at a certain frequency (eg every 6 hours). For restart tests, it is useful to be able to write a restart at the end of the run in addition to a set frequency. For example, a restart after 3 hours and another at the end of hour 4. 

Currently this can only be accomplished by setting restart_n=1 and restart_option=nhours, which would require 2 extra restarts to be written. For the benchmark configurations, these restarts are both large and time-consuming to write. 

There is also a legacy option present in the mom_cap currently to not use alarms to control restart behaviour. This can be removed because it is no longer used.

**Comment by DeniseWorthen** [comment]
@jiandewang is this issue really closed? It would have required changes to the mom cap.

**Comment by jiandewang** [comment]
> @jiandewang is this issue really closed? It would have required changes to the mom cap.

sorry my bad, re-open it

**Comment by NickSzapiro-NOAA** [comment]
This is closed in https://github.com/NOAA-EMC/MOM6/pull/133, right?

**Comment by jiandewang** [comment]
close it
